site_name: DetectMate Library
site_url: https://ait-detectmate.github.io/DetectMateLibrary/

theme:
  name: material # windmill is auch cool

nav:
  - Home: index.md

  - User Guide:
    - What is DetectMate?: user_guide/what_is_detectmate.md
    - Installation: user_guide/installation.md
    - Basic knowledge: user_guide/basic_knowledge.md
    - Quickstart: user_guide/quickstart.md
    - Tutorial (end-to-end): user_guide/tutorial.md

  - Advanced Guide:
    - Overall architecture: advanced/overall_architecture.md
    - Components:
      - Schemas: schemas.md
      - Federation: federation.md
      - Parsers: parsers.md
      - Detectors: detectors.md
      - Alert Aggregation: alert_aggregator.md
    - Parser types:
      - Template Matcher: parsers/template_matcher.md
      - Template Tree Matcher: parsers/template_tree_matcher.md
      - Json Parser: parsers/json_parser.md
      - LogBatcher Parser: parsers/logbatcher_parser.md
      - Auto Parser: parsers/auto_parser.md
      - Drain Parser: parsers/drain_parser.md
    - Detector types:
      - Random Detector: detectors/random_detector.md
      - New Value: detectors/new_value.md
      - Combo Detector: detectors/combo.md
      - New Event: detectors/new_event.md
      - Event Sequence: detectors/event_sequence.md
      - Rule Based: detectors/rule_based.md
      - BiGram Frequency: detectors/bigram_frequency.md
      - CharSet: detectors/charset.md
      - Value Range: detectors/value_range.md
      - Deeplog Detector: detectors/deeplog.md
      - LogBert Detector: detectors/logbert.md
      - SCVS Detector: detectors/scvs_detector.md
      - ECVC Detector: detectors/ecvc_detector.md
    - Alert Aggregation methods:
      - Basic Concat: alert_aggregators/basic_concatenation.md
    - Helpers:
      - From: helper/from.md
      - To: helper/to.md
      - FromTo: helper/fromto.md
    - Auxiliary:
      - Persistency: auxiliar/persistency.md
      - Data buffer: auxiliar/input_buffer.md
    - Other:
      - Log Formats: other/log_formats.md

  - How to contribute:
    - Contributing: contribution.md
    - Development: development.md
    - Release Process: release.md

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences
