site_name: DetectMate Library
site_url: https://ait-detectmate.github.io/DetectMateLibrary/

theme:
  name: material # windmill is auch cool
  features:
    - navigation.footer   # previous / next page links at the bottom of every page
  palette:
    # Light mode configuration
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Dark mode configuration
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


nav:
  - Home: index.md

  - User Guide:
    - What is DetectMate?: user_guide/what_is_detectmate.md
    - Installation: user_guide/installation.md
    - Basic knowledge: user_guide/basic_knowledge.md
    - Quickstart: user_guide/quickstart.md
    - Tutorial (end-to-end): user_guide/tutorial.md

  - Advanced Guide:
    - Overall architecture: advanced/overall_architecture.md
    - Components:
      - Schemas: schemas.md
      - Federation: federation.md
      - Parsers: parsers.md
      - Detectors: detectors.md
      - Alert Aggregation: alert_aggregator.md
    - Parser types:
      - 00_JSON Parser: parsers/json_parser.md
      - 01_Template Matcher: parsers/template_matcher.md
      - 02_Template Tree Matcher: parsers/template_tree_matcher.md
      - 03_Auto Parser: parsers/auto_parser.md
      - 04_Drain Parser: parsers/drain_parser.md
      - 05_LogBatcher Parser: parsers/logbatcher_parser.md
    - Detector types:
      - 00_Random Detector: detectors/random_detector.md
      - 01_Rule Detector: detectors/rule_based.md
      - 02_New Event Detector: detectors/new_event.md
      - 03_New Value Detector: detectors/new_value.md
      - 04_New Value Combo Detector: detectors/combo.md
      - 05_Value Range Detector: detectors/value_range.md
      - 06_Charset Detector: detectors/charset.md
      - 07_Event Sequence Detector: detectors/event_sequence.md
      - 08_Bigram Frequency Detector: detectors/bigram_frequency.md
      - 09_SCVS Detector: detectors/scvs_detector.md
      - 10_ECVC Detector: detectors/ecvc_detector.md
      - 11_DeepLog Detector: detectors/deeplog.md
      - 12_LogBERT Detector: detectors/logbert.md
    - Alert Aggregation methods:
      - 00_Basic Concat: alert_aggregators/basic_concatenation.md
    - Helpers:
      - FromTo: helper/from_to.md
    - Auxiliary:
      - Persistency: auxiliar/persistency.md
      - Data buffer: auxiliar/input_buffer.md
    - Other:
      - Log Formats: other/log_formats.md

  - How to contribute:
    - Contributing: contribution.md
    - Development: development.md
    - Release Process: release.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true
  - pymdownx.superfences
