[project]
name = "detectmatelibrary"
description = "DetectMate Library for log processing components"
readme = {file = "README.md", content-type = "text/markdown"}
dynamic = ["version"]
authors = [{"name" = "André García Gómez"}, {"name" = "Viktor Beck"}, {"name" = "Thorina Boenke"},
    {"name" = "Wolfgang Hotwagner"}, {"name" = "Anna Erdi"}, {"name" = "Ernst Leierzopf"}]
license = "EUPL-1.2"
requires-python = ">=3.12"
dependencies = [
    "protobuf>=6.32.1",
    "pydantic>=2.13.3",
    "pyyaml>=6.0.3",
    "regex>=2025.11.3",
    "numpy>=2.3.2",
    "detectmateperformance>=0.1.0",
    "msgpack>=1.0.0",
    "fsspec>=2024.1.0",
    "pyarrow>=24.0.0",
]

[dependency-groups]
# install with all the dev dependencies:  uv pip install --group dev
dev = [
    "mike>=2.2.0",
    "prek>=0.3.10",
    "pytest>=8.4.2",
    "pytest-cov>=6.2.1",
    "detectmatelibrary[full]",
]

[project.optional-dependencies]
llm = [
    "openai>=2.26.0",
    "tenacity>=9.1.4",
    "scipy>=1.17.1",
    "scikit-learn>=1.8.0",
    "tiktoken>=0.12.0",
    "pandas>=2.3.2",
]
dataframes = [
    "pandas>=2.3.2",
    "polars>=1.40.1",
]
polars-rtcompat = [
    "polars[rtcompat]>=1.38.1",
]
# install all optional extras at once:  uv pip install detectmatelibrary[full]
full = [
    "detectmatelibrary[llm]",
    "detectmatelibrary[dataframes]",
    "detectmatelibrary[polars-rtcompat]",
]

[tool.setuptools.dynamic]
version = {attr = "detectmatelibrary.metadata.__version__"}

[project.urls]
Homepage = "https://ait-detectmate.github.io/DetectMateLibrary/latest"
Repository = "https://github.com/ait-detectmate/DetectMateLibrary"

[build-system]
requires = ["setuptools>=82.0.1", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src", "."]
include = ["detectmatelibrary*"]

[project.scripts]
mate = "detectmatelibrary_tools.workspace.create_workspace:main"

[[tool.mypy.overrides]]
module = "detectmatelibrary.schemas.schemas_pb2"
ignore_errors = true
