# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: schemas.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rschemas.proto\"\x1d\n\x06Schema\x12\x13\n\x0b__version__\x18\x01 \x01(\t\"p\n\tLogSchema\x12\x13\n\x0b__version__\x18\x01 \x01(\t\x12\x12\n\x05logID\x18\x02 \x01(\x05H\x00\x88\x01\x01\x12\x0b\n\x03log\x18\x03 \x01(\t\x12\x11\n\tlogSource\x18\x04 \x01(\t\x12\x10\n\x08hostname\x18\x05 \x01(\tB\x08\n\x06_logID\"\xcb\x03\n\x0cParserSchema\x12\x13\n\x0b__version__\x18\x01 \x01(\t\x12\x12\n\nparserType\x18\x02 \x01(\t\x12\x10\n\x08parserID\x18\x03 \x01(\t\x12\x14\n\x07\x45ventID\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12\x10\n\x08template\x18\x05 \x01(\t\x12\x11\n\tvariables\x18\x06 \x03(\t\x12\x18\n\x0bparsedLogID\x18\x07 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05logID\x18\x08 \x01(\x05H\x02\x88\x01\x01\x12\x0b\n\x03log\x18\t \x01(\t\x12\x41\n\x12logFormatVariables\x18\n \x03(\x0b\x32%.ParserSchema.LogFormatVariablesEntry\x12\x1e\n\x11receivedTimestamp\x18\x0b \x01(\x05H\x03\x88\x01\x01\x12\x1c\n\x0fparsedTimestamp\x18\x0c \x01(\x05H\x04\x88\x01\x01\x1a\x39\n\x17LogFormatVariablesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\n\n\x08_EventIDB\x0e\n\x0c_parsedLogIDB\x08\n\x06_logIDB\x14\n\x12_receivedTimestampB\x12\n\x10_parsedTimestamp\"\xc9\x02\n\x0e\x44\x65tectorSchema\x12\x13\n\x0b__version__\x18\x01 \x01(\t\x12\x12\n\ndetectorID\x18\x02 \x01(\t\x12\x14\n\x0c\x64\x65tectorType\x18\x03 \x01(\t\x12\x14\n\x07\x61lertID\x18\x04 \x01(\x05H\x00\x88\x01\x01\x12\x1f\n\x12\x64\x65tectionTimestamp\x18\x05 \x01(\x05H\x01\x88\x01\x01\x12\x0e\n\x06logIDs\x18\x06 \x03(\x05\x12\x17\n\x0fpredictionLabel\x18\x07 \x01(\x08\x12\r\n\x05score\x18\x08 \x01(\x02\x12\x1b\n\x13\x65xtractedTimestamps\x18\t \x03(\x05\x12\x13\n\x0b\x64\x65scription\x18\n \x01(\t\x12\x1e\n\x11receivedTimestamp\x18\x0b \x01(\x05H\x02\x88\x01\x01\x42\n\n\x08_alertIDB\x15\n\x13_detectionTimestampB\x14\n\x12_receivedTimestampb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'schemas_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PARSERSCHEMA_LOGFORMATVARIABLESENTRY._options = None
  _PARSERSCHEMA_LOGFORMATVARIABLESENTRY._serialized_options = b'8\001'
  _SCHEMA._serialized_start=17
  _SCHEMA._serialized_end=46
  _LOGSCHEMA._serialized_start=48
  _LOGSCHEMA._serialized_end=160
  _PARSERSCHEMA._serialized_start=163
  _PARSERSCHEMA._serialized_end=622
  _PARSERSCHEMA_LOGFORMATVARIABLESENTRY._serialized_start=485
  _PARSERSCHEMA_LOGFORMATVARIABLESENTRY._serialized_end=542
  _DETECTORSCHEMA._serialized_start=625
  _DETECTORSCHEMA._serialized_end=954
# @@protoc_insertion_point(module_scope)
